
project_id = "uxcjewylcwcgmrnzdguu"

[functions.get-exchange-rates]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.save-secret]
verify_jwt = true

[functions.test-webhook]
verify_jwt = true

[functions.save-stripe-key]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true
