// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxcjewylcwcgmrnzdguu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4Y2pld3lsY3djZ21ybnpkZ3V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzYzOTcsImV4cCI6MjA2MDM1MjM5N30.96UE6Xf-MTrMEUYlr4NSxDujCWVaV8bdrMYsmJlIEc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);